### ISSUE TITLE
the example of  json output in console is {} ?

### ISSUE THREAD

**Issue by youZhuang** [mlomb/MetaCPP#1]

**Comment by youZhuang** [comment]
I fixed the compile errors.But the example output of json is 
`{}
The serialization was successful!`.

I found this code can not work.
`Type* type = TypeInfo<T>::TYPE;`

**Comment by mlomb** [comment]
What structure are you trying to serialize?

**Comment by youZhuang** [comment]
The structures in `objects.hpp` file

**Comment by mlomb** [comment]
I don't have a proper setup to test right now.
At the time, I tested this with GCC on Linux and MSVC, are you using another compiler?

**Comment by youZhuang** [comment]
Thank you. I have a try to use GCC.
