### ISSUE TITLE
Clang12 & ninja cmake support

### ISSUE THREAD

**Issue by Hexlord** [mlomb/MetaCPP#2]
**Expected behaviour**: clang 12 ninja build works correctly
**Actual behaviour**: it does not compile
So I had to make these (https://github.com/Hexlord/MetaCPP/commit/34172adc60e0931ed52913ddaa8377b0aa8c69a5) changes to make it compile under linux with latest clang (I build clang from sources). Feel free to pull them if you agree.

Note that for ninja to work the generated files must reside in some target, otherwise a rule is expected to make them.

I also fixed delete void* in your code, it is not correct (maybe it is on MSVS, as part of some extension I know nothing of), so I added destructor support, but I used c++17 features to call destructor with qualified name (otherwise I would need to pass non-qual name to ~T() for your mustache, which I had no intention of.

And thanks for this great tool! I came from metareflection, as yours already supports templates, I hope to expand it for my use-case, I will try to share useful bits.

**Comment by Hexlord** [comment]
Took me a while, added support for arrays (both char[123] and std::array), and fixed some bugs (https://github.com/Hexlord/MetaCPP/commit/99078a1ef939a91b99db505ba8c405dc2b2bf898)
Please, let me know if you are interested so I would prepare a more beautiful form of commitment (clear-up for PR)

**Comment by mlomb** [comment]
Hi, thanks for the report. I've only compiled it with MSVC, cool to know that now works on Linux!
I'll review the code in depth in a few days, but it looks good!
PS: Please use tabs instead of spaces =)

**Comment by Hexlord** [comment]
Ok, I submitted a pr (https://github.com/mlomb/MetaCPP/pull/3)
