### ISSUE TITLE
Class inside class incorrectly renders the whole class private, making the example to fail

### ISSUE THREAD

**Issue by dmikushin** [mlomb/MetaCPP#5]
Hi @Hexlord ,

This is an issue about your fork, but published here, because there is no issues board in your fork.

I understand in your commit a149fadc93c955d99579a1aae8d27498adb1b026 you are trying to filter out annoying internal types defined in the system headers. It makes sense, however I believe the this heuristics is wrong:

```c++
return decl->isClass() ? AccessSpecifier::PRIVATE : AccessSpecifier::PUBLIC;
``` 

Basically, everything that as a class inside becomes private. This is too broad, and fails the example code, because Entity is a class inside the Map class.

**Comment by dmikushin** [comment]
I think the strategic flaw of the current MetaCPP design is in the attempt to create every piece of reflection data, which is possible to create. With all your efforts put into it, it still might not work due to the compiler internal oddities. I mean to say, at a certain depth of internal logic the compiler may choose to hack the type system in a non-standard way. It's not blessed, but is likely to happen for the sake of taking reasonable shortcuts. So the MetaCPP's attempt to dig as deep as possible is doomed to fail.

I believe there is one very easy fix. MetaCPP should stop trying to create every viable type and instead create only the requested types in a lazy manner. In this case, it should never fail. If it fails, it means the user code compilation should already fail beforehand.

**Comment by Hexlord** [comment]
Hello @dmikushin, thanks for taking a look and the feedback, however I am no longer actively using MetaCPP for quite some time, so my memories of the code are hazy, perhaps it happened to work for my code base. Anyhow, I have swtiched to using LibTooling for ast inspection and never looked back, it allows you to handle any use case imaginable in any way you would want.
Regards
